### ISSUE TITLE
Wrong time format parsing for log4j2 json objects produced by log4j 2.11.0

### ISSUE THREAD

**Issue by matomer** [otros-systems/otroslogviewer#529]
The actual messages produced by log4j 2.11.0 are of the form:

```json
{
  "thread" : "NGSession 14: 127.0.0.1: compile-server",
  "level" : "ERROR",
  "loggerName" : "LOGGER",
  "message" : "msg",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "instant" : {
    "epochSecond" : 1531655721,
    "nanoOfSecond" : 34000000
  },
  "contextMap" : { },
  "threadId" : 76,
  "threadPriority" : 5
}
```

Note that instead of a "@timestamp" (and mills from epoch) there are epoch seconds and epoch nanos.
But Otros fails to parse it and instead gives the UNIX start date (1970 ...) for every event.

Libraries used:
```groovy
    compile 'org.apache.logging.log4j:log4j-api:2.11.0'
    compile 'org.apache.logging.log4j:log4j-core:2.11.0'
    compile 'com.fasterxml.jackson.core:jackson-core:2.9.4'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.9.4'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.4'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.4'
```

Configuration used:
```yaml
Configuration:
  Appenders:
    Console:
      name: STDOUT
      JsonLayout:
        properties: true
      
   Loggers:
    Root:
      level: debug
      AppenderRef:
        ref: STDOUT
```

Simple intellij (scala) scratch to reproduce:
```scala
import org.apache.logging.log4j.LogManager

LogManager.getLogger("LOGGER").error("msg")
```
