### ISSUE TITLE
Freeze: Formatting message with Soap message takes to long time, skipping this formatter

### ISSUE THREAD

**Issue by donatelloOo** [otros-systems/otroslogviewer#596]
This Soap Message formatter is freezing the whole app, related message can be shown in internal logs.

Formatting message with Soap message takes to long time, skipping this formatter

Disabling it is indeed solving the freeze issue

**Comment by svennissel** [comment]
Can you append a example Logfile with a working parser?

**Comment by benlazaro** [comment]
@donatelloOo it would be very helpful to get the steps for reproducing this issue so that we can get it fixed.
Can you provide the app version where this was first encountered?
Can you also provide an example log file (as @svennissel previously requested) so that we can try and reproduce it? We will also use that file to test the fixed code.

**Comment by donatelloOo** [comment]
I am reproducing it using OLV 1.4.15 with Socket Listener + Log4j2 Json Parser.
Thus, I don't have a file to share, but it can be reproduced every time for a log4j2 producer with following (YAML) configuration:
```
Configuration:
  status: info
  monitorInterval: 300
  
  properties:
    property:
      name: AsyncLogger.ThreadNameStrategy
      value: UNCACHED

  appenders:
    Socket:
      name: SocketJsonAppender
      host: localhost
      port: 50505
      connectTimeoutMillis: 3000
      JsonLayout:
        eventEol: true
        compact: true
        charset: UTF-8
        endOfLine: "\n"
        properties: true
        locationInfo: true
        includeStacktrace: true
        stacktraceAsString: true

    Root:
      level: info
      AppenderRef:
        ref: SocketJsonAppender
```
